-- **********************************************************************
-- * Creates database for AcmeWorld Java EE 7 application
-- * 
-- * Author: J. Juneau
-- **********************************************************************
CREATE TABLE PARK (ID DECIMAL(5) NOT NULL, "NAME" VARCHAR(150), DESCRIPTION VARCHAR(2000), PRIMARY KEY (ID));
CREATE TABLE PARK_ADMISSION (ID DECIMAL(5) NOT NULL, PARK_ID DECIMAL(5), ADULT_ADMISSION DECIMAL(5), CHILD_ADMISSION DECIMAL(5), PRIMARY KEY (ID));
CREATE TABLE PARK_RESERVATION (ID DECIMAL(5) NOT NULL, FIRST_NAME VARCHAR(60), LAST_NAME VARCHAR(60), NUM_ADULTS DECIMAL(5), NUM_CHILD DECIMAL(5), NUM_DAYS DECIMAL(5), TRIP_START_DATE DATE, ENTER_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE RESERVATION_SCHEDULE (ID DECIMAL(5) NOT NULL, RESERVATION_ID DECIMAL(5), VACATION_DAY DECIMAL(5), PARK_ID DECIMAL(5), NOTES CLOB(2147483647), PRIMARY KEY (ID));
CREATE TABLE RESTAURANT (ID DECIMAL(5) NOT NULL, "NAME" VARCHAR(150), DESCRIPTION CLOB(2147483647), PARK_ID DECIMAL(5), PRIMARY KEY (ID));
CREATE TABLE RESTAURANT_RESERVATION (ID DECIMAL(5) NOT NULL, RESTAURANT_ID DECIMAL(5), RESERVATION_ID DECIMAL(5), RESERVATION_DATE DATE, NUMBER_OF_PEOPLE DECIMAL(5), PRIMARY KEY (ID));

INSERT INTO ACMEUSER.PARK (ID, "NAME", DESCRIPTION) 
	VALUES (1, 'ACME WONDER', 'WHERE STORYBOOKS COME TO LIFE');
INSERT INTO ACMEUSER.PARK (ID, "NAME", DESCRIPTION) 
	VALUES (2, 'ACME COMPUTER SCIENCE', 'JOURNEY INTO THE EXCITING WORLD OF COMPUTER SCIENCE');
INSERT INTO ACMEUSER.PARK_ADMISSION (ID, PARK_ID, ADULT_ADMISSION, CHILD_ADMISSION) 
	VALUES (1, 1, 35, 25);
INSERT INTO ACMEUSER.PARK_ADMISSION (ID, PARK_ID, ADULT_ADMISSION, CHILD_ADMISSION) 
	VALUES (2, 2, 30, 20);
INSERT INTO ACMEUSER.PARK_RESERVATION (ID, FIRST_NAME, LAST_NAME, NUM_ADULTS, NUM_CHILD, NUM_DAYS, TRIP_START_DATE, ENTER_DATE) 
	VALUES (1, 'Illinois', 'JUG', 15, 0, 30, '2014-05-13', '2014-05-13');
INSERT INTO ACMEUSER.RESTAURANT (ID, "NAME", DESCRIPTION, PARK_ID) 
	VALUES (1, 'JUNEAUS', 'FINE CUISINE', 2);
INSERT INTO ACMEUSER.RESTAURANT (ID, "NAME", DESCRIPTION, PARK_ID) 
	VALUES (2, 'ACME WORLD CAFE', 'FINE CUISINE', 1);
INSERT INTO ACMEUSER.RESERVATION_SCHEDULE (ID, RESERVATION_ID, VACATION_DAY, PARK_ID, NOTES) 
	VALUES (1, 1, 1, 1, 'FUN DAY AT THE PARK');
INSERT INTO ACMEUSER.RESERVATION_SCHEDULE (ID, RESERVATION_ID, VACATION_DAY, PARK_ID, NOTES) 
	VALUES (2, 1, 2, 2, 'FUN DAY LEARNING ABOUT JAVA');
INSERT INTO ACMEUSER.RESERVATION_SCHEDULE (ID, RESERVATION_ID, VACATION_DAY, PARK_ID, NOTES) 
	VALUES (3, 1, 3, 1, 'LAST DAY OF FUN FOR THIS TRIP');





